version: "3.9"
services:
  app:
    build: .
    ports:
      - 3000:3000
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data     
volumes:
  db-data: