name: Test Coveralls

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

env:
  DBLINK: ${{ secrets.DBLINK }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
  TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
  TWILIO_SERVICE_SID: ${{ secrets.TWILIO_SERVICE_SID }}
  TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: npm install
        run: |
          npm install

      - name: Test with Jest
        run: |
          npm run test

      - name: Generate coverage information
        run: |
          npm run test:coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flags: --debug