on: ['push', 'pull_request']

name: Test Coveralls

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: npm install
        run: |
          npm install

      - name: Test with Jest
        run: |
          npm run test

      - name: Test coverage with Jest
        run: |
          npm run test:coverage

      - name: Coveralls

        run: env GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} npm run coverage --if-present
